### ISSUE TITLE
Unable to set redemption option through node createOrder method

### ISSUE THREAD

**Issue by sanketrelfor** [GiftRocket/giftrocket-node#2]
I am using sandbox env for now and experienced one issue while setting redeption_method option. My passed redemption option didn't get used to the gift card.

`
client.createOrder({
  'funding_source_id': '5AU166FKLKN9',
  'gifts': [
    {
      'amount': 1,
      'message': 'Good Job!',
      'recipient': {
        'email': 'abc@test.com',
        'name': 'Testing',
        'delivery_method': 'EMAIL',
        'redemption_methods': ['OKMHM2X2OHYV']
      },
      'style_id': 'TNGH8TWKINA4'
    }
  ]
}, function (err, results) {
  console.log(err);
  console.log(JSON.stringify(results, null, 2));
});
`

I am passing redemption option of Amazon but all options are enabled for the user.

**Comment by Bpless** [comment]
This is a function of the specified amount ($1).  Amazon does not accept that particular denomination.  

Allowed denominations are specified in the catalog endpoint.  

It is the case that, rather than failing in the case of a bad catalog item, the order endpoint optimistically attempts to create a gift with allowed items.
